# Database Configuration
spring.datasource.url=${jdbc:mysql://mysql-56b661e-prateekshapandey643-868c.h.aivencloud.com:20369/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA / HIBERNATE
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL dialect (important for cloud)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =====================
# SERVER CONFIG (RENDER FIX)
# =====================
server.port=${PORT:8082}